blank_issues_enabled: false
contact_links:
  - name: Questions and support
    url: https://github.com/agopalareddyagopalareddy/agopalareddy.github.io/discussions
    about: Please ask and answer questions here.
