name: CI

on:
  pull_request:
  push:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true


      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Enable Corepack
        run: corepack enable
      - name: Use pnpm 9
        run: corepack prepare pnpm@9 --activate

      - name: Install Node deps
        run: pnpm install --no-frozen-lockfile

      - name: Build JS
        run: pnpm run build:js

      - name: Build Jekyll
        run: bundle exec jekyll build --config _config.yml,_config.dev.yml --verbose

      - name: Verify site output
        run: test -f _site/index.html

      - name: HTML Proofer (internal links)
        continue-on-error: true
        run: |
          gem install html-proofer --no-document
          htmlproofer ./_site --disable-external --allow_hash_href --check-html
